length = 18

[01]
alt_title = "अर्जुन-विषाद-योगः"
length = 47

[02]
alt_title = "साङ्ख्य-योगः सर्व-गीतार्थ-सूत्रणम्"
length = 72

[03]
alt_title = "कर्म-योगः"
length = 43

[04]
alt_title = "ज्ञान-योगः ब्रह्मार्पण-योगः"
length = 42

[05]
alt_title = "कर्म-संन्यास-योगः स्व-स्वरूप-परिज्ञानम्"
length = 29

[06]
alt_title = "आत्म-संयम-योगः अभ्यास-योगः"
length = 47

[07]
alt_title = "ज्ञान-विज्ञान-योगः"
length = 30

[08]
alt_title = "अक्षर-पर-ब्रह्म-योगः"
length = 28

[09]
alt_title = "राज-विद्या-राज-गुह्य-योगः"
length = 34

[10]
alt_title = "विभूति-विस्तार-योगः"
length = 42

[11]
alt_title = "विश्व-रूप-दर्शन-योगः"
length = 55

[12]
alt_title = "भक्ति-योगः"
length = 20

[13]
alt_title = "क्षेत्र-क्षेत्रज्ञ-योगः प्रकृति-पुरुष-विवेक-योगः"
length = 34

[14]
alt_title = "गुण-त्रय-विभाग-योगः"
length = 27

[15]
alt_title = "पुरुषोत्तम-योगः"
length = 20

[16]
alt_title = "दैवासुर-सम्पद्-विभाग-योगः"
length = 24

[17]
alt_title = "श्रद्धा-त्रय-विभाग-योगः"
length = 28

[18]
alt_title = "मोक्ष-संन्यास-योगः"
length = 78

